
[ env ]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0

# Not a fan on the buttonless design
# you can uncomment it if you want
# decorations = "Buttonless"

opacity = 0.8
blur = true

[font]
normal.family = "ComicShannsMono Nerd Font"

#regular
size = 9

[general]
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

# ~/.config/alacritty/themes/themes/cyberdream.toml
    # "~/.config/alacritty/themes/themes/omni.toml"
